version: '3'

services:

  mysql:
    container_name: mysql-jiamu      # 指定容器的名称
    image: mysql:latest                   # 指定镜像和版本
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "12400:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 991120zsy
    volumes:
      - "./mysql/data:/var/lib/mysql"           # 挂载数据目录


  web:
    image: java:8
    tty: true
    container_name: web-jiamu
    ports:
      - "8080:8080"
    volumes:
      - "./jar:/app"
      - "./web/data:/data"           # 挂载数据目录
      - "./web/log:/log"
    links:
      - "mysql:mysql"



